# This is a basic workflow to help you get started with Actions

name: update-rugby-data

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
    schedule:
        - cron: '0 0 * * *'

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    update-rugby-data:
        runs-on: ubuntu-20.04
        permissions:
            contents: write
        env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: |
                sudo apt-get install libcurl4-openssl-dev
            
            - uses: r-lib/actions/setup-r@v2

            - uses: r-lib/actions/setup-renv@v2

            - name: Fetch latest data
              run: Rscript rugby.R

            - name: Commit Results
              run: |
                git config --local user.name "$GITHUB_ACTOR"
                git config --local user.email "<>"
                git add last_date.csv rugby.csv
                timestamp=$(date -u)
                git commit -m "Latest Update: ${timestamp}" || exit 0
                git push origin
