# This is a basic workflow to help you get started with Actions

name: update-rugby-data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
    schedule:
        - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    update-rugby-data:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            
            - uses: r-lib/actions/setup-r@v2

            - uses: r-lib/actions/setup-r-dependencies@v2
            
            # Runs a single command using the runners shell
            - name: Run a one-line script
              run: echo Hello, world!
            
            # Runs a set of commands using the runners shell
            - name: Run a multi-line script
              run: |
                echo Add other actions to build,
                echo test, and deploy your project.
