name: update-rugby-data

on:
    # runs at 23:29 each Monday
    # job takes around 5 minutes to complete
    push:
    schedule:
        - cron: '29 23 * * 1'
    workflow_dispatch:

jobs:
    update-rugby-data:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            # install libcurl on ubuntu
            # without this, the package `curl` fails to install
            - name: Install dependencies
              run: |
                sudo apt-get install libcurl4-openssl-dev
            
            - uses: r-lib/actions/setup-r@v2

            - uses: r-lib/actions/setup-renv@v2

            - name: Fetch latest data
              run: Rscript rugby.R

            - name: Commit Results
              run: |
                git config --local user.name "$GITHUB_ACTOR"
                git config --local user.email "<>"
                timestamp=$(date -u)
                git commit last_date.csv -m "Latest last_date.csv Update: ${timestamp}" || exit 0
                timestamp=$(date -u)
                git commit rugby.csv -m "Latest rugby.csv Update: ${timestamp}" || exit 0
                git push origin
