name: update-rugby-data

on:
    # runs at 23:29 UTC each Monday
    push:
    schedule:
        - cron: '29 23 * * 1'
    workflow_dispatch:

jobs:
    update-rugby-data:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            # install libcurl on ubuntu
            # without this, the package `curl` fails to install
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install libcurl4-openssl-dev

            - name: Set up R
              uses: r-lib/actions/setup-r@v2

            - name: Set up renv
              uses: r-lib/actions/setup-renv@v2

            - name: Cache R packages
              uses: actions/cache@v3
              with:
                path: ${{ env.RENV_PATHS_ROOT }}
                key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
                restore-keys: |
                    ${{ runner.os }}-renv-

            - name: Restore R packages
              run: |
                if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
                renv::restore()

            - name: Fetch latest data
              run: Rscript rugby.R

            - name: Commit Results
              run: |
                git config --local user.name "$GITHUB_ACTOR"
                git config --local user.email "<>"
                git add rugby.csv
                timestamp=$(date -u)
                git commit -m "Latest Update: ${timestamp}" || exit 0
                git push origin
